ToDoMVC/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ToDoMVC.Models;

namespace ToDoMVC.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        ToDoContext db;
        public AdminController(ToDoContext context)
        {
            db = context;
        }

        [ActionName("Index")]
        public async Task<IActionResult> Index()
        {
            var lists = await db.Titles
                .Include(t => t.User)
                .Include(t => t.Tasks)
                .ToListAsync();
            return View(lists);
        }
    }
}

ToDoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <title>My ToDo list</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-action="Index" asp-controller="Home">To-Do</a>    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Admin">All Lists </a>
            </li>

            @if (User.Identity.IsAuthenticated)
            {
                <li class="nav-item">
                    <a class="nav-link" asp-action="Logout" asp-controller="Account">Logout</a>
                </li>

            }

        </ul>

    </div>
</nav>

<body>

    <div class="container">

        <div class="starter-template">

            @RenderBody()
                        

        </div>

    </div>

</body>

</html>