ToDoMVC/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoMVC.Models;
using Task = ToDoMVC.Models.Task;

namespace ToDoMVC.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        ToDoContext db;
        public TasksController(ToDoContext context)
        {
            db = context;
        } 
        
        // Создание нового Действия
        [HttpPost]        
        public async Task<IActionResult> Create(Task task)
        {
            db.Tasks.Add(task);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        //------------

        // Редактирование 
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Task task = await db.Tasks.FirstOrDefaultAsync(p => p.Id == id);
                if (task != null)
                    return View(task);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int? id, string Name)
        {
            if (id != null)
            {
                Task task = await db.Tasks.FirstOrDefaultAsync(p => p.Id == id);
                if (task != null)
                {
                    task.Name = Name;
                    db.Tasks.Update(task);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
            }
            return NotFound();
        }
        // ----------------

        // Удаление
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if(id != null)
            {               
                Task task = new Task { Id = id.Value };
                db.Entry(task).State = EntityState.Deleted;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
                
            }
            return NotFound();
        }
        // ---------------

        public async Task<IActionResult> ToggleStatus(int? id)
        {
            if (id != null)
            {
                if (id != null)
                {
                    Task task = await db.Tasks.FirstOrDefaultAsync(p => p.Id == id);
                    if (task != null)
                    {
                        if(task.Done)
                        {
                            task.Done = false;
                            db.Tasks.Update(task);
                            //await db.SaveChangesAsync();
                        }
                        else
                        {
                            task.Done = true;
                            db.Tasks.Update(task);
                            //await db.SaveChangesAsync();
                        }
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index", "Home");
                    }
                }                
            }
            return NotFound();
        }

    }
}

ToDoMVC/Controllers/TitlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoMVC.Models;

namespace ToDoMVC.Controllers
{
    [Authorize]
    public class TitlesController : Controller
    {
        ToDoContext db;
        public TitlesController(ToDoContext context)
        {
            db = context;
        }

        // Создание нового Действия
        public IActionResult Create()
        {
            User user = db.Users.FirstOrDefault(u => u.Email == User.Identity.Name);
            ViewData["id"] = user.Id;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Title title)
        {
            db.Titles.Add(title);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        //------------

        // Редактирование 
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Title title = await db.Titles.FirstOrDefaultAsync(p => p.Id == id);
                if (title != null)
                    return View(title);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int? id, string Name)
        {
            if (id != null)
            {
                Title title = await db.Titles.FirstOrDefaultAsync(p => p.Id == id);
                if (title != null)
                {
                    title.Name = Name;
                    db.Titles.Update(title);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
            }
            return NotFound();
        }
        // ----------------

        // Удаление
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Title title = new Title { Id = id.Value };
                db.Entry(title).State = EntityState.Deleted;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");

            }
            return NotFound();
        }

        // ---------------
    }
}

ToDoMVC/Views/Admin/Index.cshtml
@model IEnumerable<ToDoMVC.Models.Title>

<div class="container">

    <h1>To-do</h1>
    <ul class="list-group">
        @foreach (var title in Model)
        {
            <li class="list-group-item d-flex justify-content-between">
                <h3>@title.Name <small>@title.User.Name</small> </h3>

                <div class="btn-group ">
                    @Html.ActionLink("Edit", "Edit", "Titles", new { id = title.Id }, new { @class = "btn btn-outline-info " })
                    @Html.ActionLink("Delete", "Delete", "Titles", new { id = title.Id }, new { onclick = "return confirm('Вы уверены?')", @class = "btn btn-danger" })
                </div>
            </li>
            @foreach (var task in title.Tasks)
            {
                <li class="list-group-item d-flex justify-content-between @( task.Done ? "list-group-item-success" : "list-group-item-primary" ) ">
                    <h6>@task.Name</h6>
                    <div class="btn-group ">
                        @Html.ActionLink("Mark", "ToggleStatus", "Tasks", new { id = task.Id }, new { @class = "btn btn-outline-success" })
                        @Html.ActionLink("Edit", "Edit", "Tasks", new { id = task.Id }, new { @class = "btn btn-outline-info " })
                        @Html.ActionLink("Delete", "Delete", "Tasks", new { id = task.Id }, new { onclick = "return confirm('Вы уверены?')", @class = "btn btn-danger" })

                    </div>
                </li>
            }

            <form asp-action="create" asp-controller="tasks" class="form-group">
                <input type="text" name="Name" class="form-control" placeholder="Введите Заметку" />
                <input type="hidden" name="TitleId" value="@title.Id">
                <button type="submit" class="btn btn-primary">Добавить </button>
            </form>
        }
    </ul>
    @Html.ActionLink("Создать новый список", "Create", "Titles", new { }, new { @class = "btn btn-success btn-lg btn-block" })
</div>